### ISSUE TITLE
$vars: not all vars in completion

### ISSUE THREAD

**Issue by Alexey-T** [TomBraider42/cuda_autoit_helper#11]
Here must be 3 vars beginning from $d
I see only one $dd
![var](https://user-images.githubusercontent.com/4154978/29840709-925dda90-8d0b-11e7-8e34-05ce29e4db0a.png)

**Comment by TomBraider42** [comment]
Interesting, you should see no vars because you have to assign them first.
At the moment i am only looking for vars before "=".
![autoit](https://user-images.githubusercontent.com/5128016/29857359-8e740e52-8d58-11e7-8319-d70364d0737c.PNG)
Planed are all vars $..., from "Global" too, goto Defs, parse included files, ... but the time... ;)

**Comment by Alexey-T** [comment]
Ok, I see that i must write "= smth".
